def logo():

	os.system('clear')
logo = (f'''\033[1;37m                                 	
888    888          888b     d888          
888    888          8888b   d8888           
\033[1;92m888    888          88888b.d88888              
\033[1;92m8888888888 888  888 888Y88888P888.    
\033[1;37m888    888 `Y8bd8P' 888 Y888P 888           
\033[1;37m888    888   X88K   888  Y8P  888                    
\033[1;92m888    888 .d8""8b. 888   "   888                          
\033[1;92m888    888 888  888 888       888
\033[1;37m ---------------------------------------------------
 Owner    : \033[92;1mHamza
\033[97;1m GitHub   : No Need
 Status   : \033[1;91mPERSONAL
\033[97;1m Version  : 1.6
 \033[1;92m ok/cp ids will be saved in HxM folderðŸ’”
 \033[1;37m---------------------------------------------------''')
	 
print('\033[91;1mI love you I love you I love you I love you ')
print(' love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕 ')
print ( ' From -MrHamza ')
print('\033[92;1mI love you I love you I love you I love you ')
print(' love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕 ')
print ( ' From -MrHamza ')
print('\033[33;1mI love you I love you I love you I love you ')
print(' love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕 ')
print ( ' From -MrHamza ')
print(' \033[90;1mI love you I love you I love you I love you ')
print(' love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕 ')
print ( ' From -MrHamza ')
print('\033[94;1mI love you I love you I love you I love you ')
print(' love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕 ')
print ( ' From -MrHamza ')
print(' \033[92;1mlove you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕 ')
print ( ' From -MrHamza ')
print('\033[9;1m love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕 ')
print ( ' From -MrHamza ')
print(' \033[95;1mlove you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕I love you I love you I love you I love you I love you I love you I love you I love you I love 💕 ')
print ( ' From -MrHamza ')


